Ukol3
Skyllarr/PV256Android pull request #2
Opened 2016-12-28 20:09 UTC by Skyllarr

2017-01-16 22:08 UTC, vandus commented on app/src/main/java/cz/muni/fi/pv256/movio2/uco374585/ListFragment.java
> +        return view;
netreba ukladat do lokalnej premennej, ak sa nevyuzije :)

2017-01-16 22:09 UTC, vandus commented on app/src/main/java/cz/muni/fi/pv256/movio2/uco374585/ListFragment.java
> +            e.printStackTrace();
lepsie je pouzivat error log, nieco ako Log.e, print stack trace asi uplne nechces v appke vsade.
to len tak btw

2017-01-16 22:21 UTC, vandus approved these changes

2017-01-16 22:25 UTC, vandus requested changes
skus si to otvorit na tablete, klikni na prvy, druhy, treti film, a potom klikaj na tlacitko naspat. Bude to postupne prechadzat poslednymi zobrazenymi filmami, a to asi nie je uplne chcene. asi v tomto pripade nema zmysel ukladat fragmenty do backstacku.

a navyse, deje sa to preto, ze vzdy pridavas novy a novy fragment. ak uz je detail fragment zobrazeny, tak by si mala len updatenut content s novymi datami.

2017-01-17 16:38 UTC, Skyllarr commented
@vandus opravene sucasne pripomienky, do ostatnych ukolov to mergenem az po schvaleni (takze ostatne ukoly budu mat este backstack a tak)

2017-01-17 22:28 UTC, vandus approved these changes

2017-01-18 14:31 UTC, merged